#Base damage
#Range: 0.0 ~ 100.0
base_damage = 6.0
#AMP intensity bonus
#Range: 0.0 ~ 100.0
amp_bonus = 0.6
#Base intensity
#Range: 0.0 ~ 100.0
base = 1.2
#AOE intensity bonus
#Range: 0.0 ~ 100.0
aoe_bonus = 1.8
#Additional damage per amplify
#Range: 0.0 ~ 100.0
amp_damage = 3.0

