
#Screen Config
[screen]
	#The duration of GUI background color and blur radius animation in milliseconds. (0 = OFF)
	#Range: 0 ~ 800
	animationDuration = 200
	#The GUI background color in #RRGGBB or #AARRGGBB format. Default value: #66000000
	#Can be one to four values representing top left, top right, bottom right and bottom left color.
	#Multiple values produce a gradient effect, whereas one value produce a solid color.
	#When values is less than 4, the rest of the corner color will be replaced by the last value.
	backgroundColor = ["#66000000"]
	#Add blur effect to GUI background when opened, it is incompatible with OptiFine's FXAA shader and some mods.
	blurEffect = true
	#The 4-pass blur effect radius, higher values result in a small loss of performance.
	#Range: 2 ~ 18
	blurRadius = 9
	#A list of GUI screen superclasses that won't activate blur effect when opened.
	blurBlacklist = ["net.minecraft.client.gui.screens.ChatScreen"]
	#(Beta) Pause the game when inventory (also includes creative mode) opened.
	inventoryPause = false

#Tooltip Config
[tooltip]
	#Whether to enable Modern UI tooltip style, or back to vanilla style.
	enable = false
	#The tooltip FILL color in #RRGGBB or #AARRGGBB format. Default: #D4000000
	#Can be one to four values representing top left, top right, bottom right and bottom left color.
	#Multiple values produce a gradient effect, whereas one value produce a solid color.
	#When values is less than 4, the rest of the corner color will be replaced by the last value.
	colorFill = ["#D4000000"]
	#The tooltip STROKE color in #RRGGBB or #AARRGGBB format. Default: #F0AADCF0, #F0DAD0F4, #F0FFC3F7 and #F0DAD0F4
	#Can be one to four values representing top left, top right, bottom right and bottom left color.
	#Multiple values produce a gradient effect, whereas one value produce a solid color.
	#When values is less than 4, the rest of the corner color will be replaced by the last value.
	colorStroke = ["#F0AADCF0", "#F0DAD0F4", "#F0FFC3F7", "#F0DAD0F4"]
	#The duration of tooltip alpha animation in milliseconds. (0 = OFF)
	#Range: 0 ~ 800
	animationDuration = 200

#General Config
[general]
	#Play a sound effect when the game is loaded.
	ding = true
	#Control the window mode, normal mode does nothing.
	#Allowed Values: NORMAL, FULLSCREEN, FULLSCREEN_BORDERLESS, MAXIMIZED, MINIMIZED, WINDOWED, WINDOWED_BORDERLESS
	windowMode = "NORMAL"
	#UI renderer is disabled when the OpenGL capability test fails.
	#Sometimes the driver reports wrong values, you can enable this to ignore it.
	skipGLCapsError = false
	#A dialog popup is displayed when the OpenGL capability test fails.
	#Set to false to not show it. This is ignored when skipGLCapsError=true
	showGLCapsError = true

#View system config, only applied to Modern UI Core.
[view]
	#Force layout direction to RTL, otherwise, the current Locale setting.
	forceRtl = false
	#The global font scale used with sp units.
	#Range: 0.5 ~ 2.0
	fontScale = 1.5
	#Default scrollbar size in dips.
	#Range: 0 ~ 1024
	scrollbarSize = 8
	#Distance a touch can wander before we think the user is scrolling in dips.
	#Range: 0 ~ 1024
	touchSlop = 8
	#Minimum size of the touch target for a scrollbar in dips.
	#Range: 0 ~ 1024
	minScrollbarTouchTarget = 16
	#Minimum velocity to initiate a fling in dips per second.
	#Range: 0 ~ 32767
	minimumFlingVelocity = 50
	#Maximum velocity to initiate a fling in dips per second.
	#Range: 0 ~ 32767
	maximumFlingVelocity = 8000
	#Max distance in dips to overscroll for edge effects.
	#Range: 0 ~ 1024
	overscrollDistance = 0
	#Max distance in dips to overfling for edge effects.
	#Range: 0 ~ 1024
	overflingDistance = 12
	#Amount to scroll in response to a vertical scroll event, in dips per axis value.
	#Range: 0.0 ~ 1024.0
	verticalScrollFactor = 64.0
	#Amount to scroll in response to a horizontal scroll event, in dips per axis value.
	#Range: 0.0 ~ 1024.0
	horizontalScrollFactor = 64.0

#Font Config
[font]
	#Control the anti-aliasing of raw glyph rendering.
	antiAliasing = true
	#Control the fractional metrics of raw glyph rendering.
	#Disable for rougher fonts; Enable for smoother fonts.
	fractionalMetrics = true
	#Enable linear sampling for font atlases with mipmaps, mag filter will be always NEAREST.
	#If your fonts are not bitmap fonts, then you should keep this setting true.
	linearSampling = true
	#A set of font families with fallbacks to determine the typeface to use.
	#TrueType & OpenTrue are supported. Each element can be one of the following three cases.
	#1) Font family root name for those installed on your PC, for instance: Segoe UI
	#2) File path for external fonts on your PC, for instance: /usr/shared/fonts/x.otf
	#3) Resource location for those loaded with resource packs, for instance: modernui:font/biliw.otf
	#Using bitmap fonts should consider other text settings, default glyph size should be 16x.
	#This list is only read once when the game is loaded. A game restart is required to reload
	fontFamily = ["kubejs:font/readexpro.ttf", "modernui:font/biliw.otf", "Calibri", "Microsoft YaHei UI", "SimHei", "SansSerif"]

