
#Text Config
[text]
	#Allow text renderer to drop shadow, setting to false can improve performance.
	allowShadow = true
	#Fix resolution level at 2. When the GUI scale increases, the resolution level remains.
	#Then GUI scale should be even numbers (2, 4, 6...), based on Minecraft GUI system.
	#If your fonts are not bitmap fonts, then you should keep this setting false.
	fixedResolution = false
	#Control base font size, in GUI scaled pixels. The default and vanilla value is 8.
	#For bitmap fonts, 8 represents a glyph size of 8x or 16x if fixed resolution.
	#Range: 6.0 ~ 10.0
	baseFontSize = 8.0
	#Control vertical baseline for vanilla text layout, in GUI scaled pixels.
	#For smaller font, 6 is recommended. The default value is 7.
	#Range: 4.0 ~ 10.0
	baselineShift = 7.0
	#Super sampling can make the text more sharper with large font size or in the 3D world.
	#But perhaps it makes the path edge too blurry and difficult to read.
	superSampling = false
	#Enable to make each glyph pixel-aligned in text layout in screen space.
	#Text rendering may be better with bitmap fonts or fixed resolution or linear sampling.
	alignPixels = false
	#Set the recycle time of layout cache in seconds, using least recently used algorithm.
	#Range: 2 ~ 60
	cacheLifespan = 12
	#Set the rehash threshold of layout cache
	#Range: 0 ~ 2000
	rehashThreshold = 100
	#Control bidirectional text heuristic algorithm.
	#Range: 1 ~ 7
	textDirection = 1
	#Whether to render colored emoji or just grayscale emoji.
	colorEmoji = true
	#Whether to use bitmap replacement for non-Emoji character sequences. Restart is required.
	bitmapReplacement = false
	#Allow to use Slack or Discord shortcodes to replace Emoji character sequences in chat.
	emojiShortcodes = true
	#Control the text shadow offset for vanilla text rendering, in GUI scaled pixels.
	#Range: 0.20000000298023224 ~ 4.0
	shadowOffset = 0.8
	#Control the text outline offset for vanilla text rendering, in GUI scaled pixels.
	#Range: 0.20000000298023224 ~ 4.0
	outlineOffset = 0.5

