#
# Chain Hang Amount
#
# Effects how much the chain hangs.
# Collision will update on new chains or world loading.
#  Has no effect in multiplayer.
#Range: 0.0 ~ 1.7976931348623157E308
chainHangAmount = 9.0
#
#  Max Chain Distance
#
# Warning: Long chains can sometimes become invisible!
# Has no effect in multiplayer.
#Range: 0 ~ 32
maxChainRange = 7

