
#Visual Settings
[visual]
	#Disables the headache- and possibly seizure-inducing visual effects of Demon's Dream.
	disableDemonsDreamShaders = false
	#Disables holiday themed visual content such as familiar skins.
	disableHolidayTheming = false

#Misc Settings
[misc]
	#Sync JEI search in storage actuator.
	syncJeiSearch = false
	#If true, divination rod will render all matching blocks with an outline. Disable if it causes lag.
	divinationRodHighlightAllResults = false
	#The scan range in blocks for the divination rod. Too high might cause lags
	#Range: > 1
	divinationRodScanRange = 129

