#Adjust the default way RGB16 handles dyes
#True = RYB blending is used to mix the colors
# > Like mixing paint, the dye will be added to the existing color
# > Sneak-Click to set to dye color
# 
#False = Direct RGB value manipulation
# > Click to increase, Sneak-Click to decrease
# 
#RYB is easier to use but RGB is more precise
use_color_blend_mode = true
#In addition to Sneak+Scroll, Tool Modes can be changed with Sneak+PageUp/Down
keys_change_tool_mode = true

