#setting UBO offset
#-1 for auto setting
#maximum is limited by your gpu,the OpenGL constant:GL_MAX_UNIFORM_BUFFER_BINDINGS-1,at least 36-1
#Range: -1 ~ 128
"UBO offset" = -1
#setting block bloom
#true for effect on
#Block bloom only, does not apply to post-processing
"Block Bloom Effect" = true
#using light map for more realistic lighting
#true for light map ON
#If using the light map, the light is more realistic and avoid lights through the wall. The light is smoother when closed. It is a tradeoff.
"Using Light Map" = true
"enable colored light" = true
"enable bloom effect" = true
#using additive blend for colored lights 
#true - vivid, false - realistic
"additive effect" = false

