
["Health Bar"]
	#
	#Determines the color to use for the Health Bar.
	#
	colorHealth = "#FF0000"
	#
	#Determines the color to use for the Health Bar when the player has the poison effect.
	# You must use # in order to use hexadecimal colors, otherwise it defaults to decimal color values.
	#
	colorHealthPoisonEffect = "#8B8712"
	#
	#Determines the color to use for the Health Bar when the player has the wither effect.
	#
	colorHealthWitherEffect = "#404040"
	#
	#Determines the color to use for the Health Bar when the player is frozen.
	#
	colorHealthFrozenEffect = "#A8F7FF"

["Absorption Bar"]
	#
	#Determines the color to use for the Absorption Bar.
	#
	colorAbsorption = "#D4AF37"

["Horse Health Bar"]
	#
	#Determines the color to use for the Horse Health Bar.
	#
	colorHorseHealth = "#DA662C"

["Armor Bar"]
	#
	#Determines the color to use for the Armor Bar.
	#
	colorArmor = "#B8B9C4"

["Armor Toughness Bar"]
	#
	#Determines the color to use for the Armor Toughness Bar.
	#
	colorArmorToughness = "#749EF4"

["Air Bar"]
	#
	#Determines the color to use for the Air Bar.
	#
	colorAir = "#0094FF"

["Hunger Bar"]
	#
	#Determines the color to use for the Hunger Bar.
	#
	colorHunger = "#FF9900"
	#
	#Determines the color to use for the Hunger Bar when a food item is in hand.
	#
	colorHungerInHand = "#FF9900"
	#
	#Determines the color to use for the Hunger Bar when the player has the hunger effect.
	#
	colorHungerEffect = "#8B8712"

["Saturation Bar"]
	#
	#Determines the color to use for the Saturation Bar.
	#
	colorSaturation = "#FFDD27"
	#
	#Determines the color to use for the Saturation Bar when a food item is in hand.
	#
	colorSaturationInHand = "#FFDD27"
	#
	#Determines the color to use for the Saturation Bar when the player has the hunger effect.
	#
	colorSaturationEffect = "#FF0000"

