
[structures]

	[structures.global]
		#How flat does terrain need to be for surface structures to spawn? (in blocks) [default: 4]
		#Range: 0 ~ 64
		flatness_delta = 4
		#How many chunks need to be at least between two structures? (in chunks) [default: 5]
		#Range: 0 ~ 64
		min_structure_distance = 5

	[structures.castle]
		#Spawn Chance [default: 0.5]. 
		# 1.0 = generate the structure always, 0.0 = never generate the structure
		#Range: 0.0 ~ 1.0
		spawn_chance = 0.5
		#Spacing (in chunks) [default: 37]
		#Range: 0 ~ 200
		spacing = 37
		#Minimum Separation (in chunks) [default: 7]
		#Range: 0 ~ 200
		separation = 7

	[structures.castle_ruin]
		#Spawn Chance [default: 0.6]. 
		# 1.0 = generate the structure always, 0.0 = never generate the structure
		#Range: 0.0 ~ 1.0
		spawn_chance = 0.6
		#Spacing (in chunks) [default: 33]
		#Range: 0 ~ 200
		spacing = 33
		#Minimum Separation (in chunks) [default: 7]
		#Range: 0 ~ 200
		separation = 7

	[structures.desert_house]
		#Spawn Chance [default: 0.7]. 
		# 1.0 = generate the structure always, 0.0 = never generate the structure
		#Range: 0.0 ~ 1.0
		spawn_chance = 0.7
		#Spacing (in chunks) [default: 28]
		#Range: 0 ~ 200
		spacing = 28
		#Minimum Separation (in chunks) [default: 7]
		#Range: 0 ~ 200
		separation = 7

	[structures.forge]
		#Spawn Chance [default: 0.7]. 
		# 1.0 = generate the structure always, 0.0 = never generate the structure
		#Range: 0.0 ~ 1.0
		spawn_chance = 0.7
		#Spacing (in chunks) [default: 28]
		#Range: 0 ~ 200
		spacing = 28
		#Minimum Separation (in chunks) [default: 7]
		#Range: 0 ~ 200
		separation = 7

	[structures.player_house]
		#Spawn Chance [default: 0.7]. 
		# 1.0 = generate the structure always, 0.0 = never generate the structure
		#Range: 0.0 ~ 1.0
		spawn_chance = 0.7
		#Spacing (in chunks) [default: 28]
		#Range: 0 ~ 200
		spacing = 28
		#Minimum Separation (in chunks) [default: 7]
		#Range: 0 ~ 200
		separation = 7

	[structures.spawner_dungeon]
		#Spawn Chance [default: 0.7]. 
		# 1.0 = generate the structure always, 0.0 = never generate the structure
		#Range: 0.0 ~ 1.0
		spawn_chance = 0.7
		#Spacing (in chunks) [default: 28]
		#Range: 0 ~ 200
		spacing = 28
		#Minimum Separation (in chunks) [default: 7]
		#Range: 0 ~ 200
		separation = 7

	[structures.tower_ruin]
		#Spawn Chance [default: 0.8]. 
		# 1.0 = generate the structure always, 0.0 = never generate the structure
		#Range: 0.0 ~ 1.0
		spawn_chance = 0.8
		#Spacing (in chunks) [default: 23]
		#Range: 0 ~ 200
		spacing = 23
		#Minimum Separation (in chunks) [default: 7]
		#Range: 0 ~ 200
		separation = 7

	[structures.witch_hut]
		#Spawn Chance [default: 0.85]. 
		# 1.0 = generate the structure always, 0.0 = never generate the structure
		#Range: 0.0 ~ 1.0
		spawn_chance = 0.85
		#Spacing (in chunks) [default: 23]
		#Range: 0 ~ 200
		spacing = 23
		#Minimum Separation (in chunks) [default: 6]
		#Range: 0 ~ 200
		separation = 6

	[structures.big_tree]
		#Spawn Chance [default: 0.7]. 
		# 1.0 = generate the structure always, 0.0 = never generate the structure
		#Range: 0.0 ~ 1.0
		spawn_chance = 0.7
		#Spacing (in chunks) [default: 28]
		#Range: 0 ~ 200
		spacing = 28
		#Minimum Separation (in chunks) [default: 7]
		#Range: 0 ~ 200
		separation = 7

[blocks]

	[blocks.doused_torch]
		#Enable/Disable the Doused Torch Feature. If disabled Water will no longer transform normal Torches into Doused Torches. 
		# Doused Torches will however still generate in structures. [default: false]
		disable = false

